---
- name: Install dhcp server
  package:
    name: isc-dhcp-server
    state: present
  become: true

- name: Configure dhcp server interface
  template:
    src: etc-default-isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart-isc-dhcp-server
  become: true

- name: Configure dhcp server
  template:
    src: etc-dhcp-dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart-isc-dhcp-server
  become: true
